apiVersion: apps/v1
kind: Deployment
metadata:
  name: logistica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logistica
  template:
    metadata:
      labels:
        app: logistica
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: logistica
        image: docker.io/brunoferreirag/logistica:latest
        ports:
        - containerPort: 8004
          name: logistica
        resources:
          requests:
            memory: "128Mi"
            cpu: "10m"
          limits:
            memory: "512Mi"
            cpu: "512m"
---
apiVersion: v1
kind: Service
metadata:
  name: logistica
spec:
  type: LoadBalancer 
  ports:
    - name: logistica
      protocol: TCP
      port: 8004
  selector:
    app: logistica
---